version: "3"

networks:
    laravel:

services:
    nginx:
        # platform: linux/x86_64
        image: nginx:stable-alpine
        container_name: nginx-8
        ports:
            - "80:80"
        volumes:
            - ../:/var/www/html/
            - ./nginx/:/etc/nginx/conf.d/
        depends_on:
            - php
        networks:
            - laravel

    php:
        # platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: azzam
                uid: 1000
        container_name: php-8
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ../:/var/www/html/
        ports:
            - "9000:9000"
        networks:
            - laravel

    mysql:
        image: mysql:latest
        container_name: mysql-8
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: azzam
            MYSQL_PASSWORD: 123456
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

volumes:
    mysql-data: